# Generated by Django 3.2.4 on 2021-07-07 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_choices'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choices',
        ),
    ]
